import {
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rename,
  rm,
  unlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

import {
  checkVersions,
  synchronizeVersions,
  validateVersion,
  VersionError,
} from "./manage-version.mjs";

const temporaryRoots = [];

function cargoFixture(version) {
  return `[workspace]
members = []

[workspace.package]
# Preserve this comment and the following blank line.
version = "${version}"

[profile.release]
lto = "thin"
`;
}

function lockFixture({ appVersion, coreVersion, sourceApp = false }) {
  return `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "ai-router-app"
version = "${appVersion}"
${sourceApp ? 'source = "registry+https://example.invalid/index"\n' : ""}dependencies = [
 "router-core",
]

[[package]]
name = "router-core"
version = "${coreVersion}"

[[package]]
name = "unrelated-dependency"
version = "0.1.1"
source = "registry+https://example.invalid/index"
`;
}

function packageFixture(version) {
  return `{
  "name": "fixture",
  "version": "${version}",
  "metadata": {
    "version": "leave-this-nested-value"
  }
}
`;
}

async function projectFixture({
  appLockVersion = "0.1.0",
  cargoVersion = "0.1.0",
  coreLockVersion = "0.1.0",
  packageVersion = "0.1.0",
  tauriVersion = "0.1.1",
} = {}) {
  const root = await mkdtemp(join(tmpdir(), "ai-router-version-"));
  temporaryRoots.push(root);
  await mkdir(join(root, "src-tauri"));
  await Promise.all([
    writeFile(join(root, "Cargo.toml"), cargoFixture(cargoVersion)),
    writeFile(
      join(root, "Cargo.lock"),
      lockFixture({ appVersion: appLockVersion, coreVersion: coreLockVersion }),
    ),
    writeFile(join(root, "package.json"), packageFixture(packageVersion)),
    writeFile(
      join(root, "src-tauri", "tauri.conf.json"),
      `${JSON.stringify({ version: tauriVersion }, null, 2)}\n`,
    ),
  ]);
  return root;
}

async function managedContents(root) {
  const [cargo, cargoLock, packageJson] = await Promise.all([
    readFile(join(root, "Cargo.toml"), "utf8"),
    readFile(join(root, "Cargo.lock"), "utf8"),
    readFile(join(root, "package.json"), "utf8"),
  ]);
  return { cargo, cargoLock, packageJson };
}

async function temporarySiblings(root) {
  const files = await readdir(root);
  return files.filter((file) => file.endsWith(".tmp"));
}

afterEach(async () => {
  await Promise.all(
    temporaryRoots
      .splice(0)
      .map((root) => rm(root, { force: true, recursive: true })),
  );
});

describe("version validation", () => {
  it.each(["0.0.0", "1.2.3"])("accepts canonical SemVer %s", (version) => {
    expect(validateVersion(version, "fixture.json")).toBe(version);
  });

  it.each([
    "v1.2.3",
    " 1.2.3",
    "1.2.3 ",
    "01.2.3",
    "1.02.3",
    "1.2.03",
    "1.2.3-01",
    "1.2",
    "1.2.3-",
    "1.2.3+",
    "1.2.3-alpha..1",
    "1.2.3+build..1",
    "1.2.3_alpha",
    "1.2.3+build+again",
    "1.2.3-alpha.1",
    "1.2.3+build.5",
  ])("rejects noncanonical or invalid version %s", (version) => {
    expect(() => validateVersion(version, "fixture.json")).toThrow(
      VersionError,
    );
  });

  it("rejects non-string and over-limit inputs before parsing", () => {
    expect(() => validateVersion(123, "fixture.json")).toThrow(VersionError);

    const adversarialVersion = `1.2.3-${"a.".repeat(128)}!`;
    expect(adversarialVersion.length).toBeGreaterThan(256);
    expect(() => validateVersion(adversarialVersion, "fixture.json")).toThrow(
      VersionError,
    );
  });
});

describe("managed app versions", () => {
  it("synchronizes every projection and preserves unrelated bytes", async () => {
    const root = await projectFixture();

    await expect(synchronizeVersions(root)).resolves.toBe("0.1.1");
    await expect(checkVersions(root)).resolves.toBe("0.1.1");

    const contents = await managedContents(root);
    expect(contents.cargo).toBe(cargoFixture("0.1.1"));
    expect(contents.packageJson).toBe(packageFixture("0.1.1"));
    expect(contents.cargoLock).toBe(
      lockFixture({ appVersion: "0.1.1", coreVersion: "0.1.1" }),
    );
    expect(contents.packageJson).toContain(
      '"version": "leave-this-nested-value"',
    );
    expect(contents.cargoLock).toContain(
      'name = "unrelated-dependency"\nversion = "0.1.1"',
    );
  });

  it("is byte-idempotent after the first synchronization", async () => {
    const root = await projectFixture();

    await synchronizeVersions(root);
    const first = await managedContents(root);
    await synchronizeVersions(root);

    await expect(managedContents(root)).resolves.toEqual(first);
    await expect(temporarySiblings(root)).resolves.toEqual([]);
  });

  it("preserves CRLF line endings while changing only managed scalars", async () => {
    const root = await projectFixture();
    await Promise.all([
      writeFile(
        join(root, "Cargo.toml"),
        cargoFixture("0.1.0").replaceAll("\n", "\r\n"),
      ),
      writeFile(
        join(root, "Cargo.lock"),
        lockFixture({ appVersion: "0.1.0", coreVersion: "0.1.0" }).replaceAll(
          "\n",
          "\r\n",
        ),
      ),
      writeFile(
        join(root, "package.json"),
        packageFixture("0.1.0").replaceAll("\n", "\r\n"),
      ),
    ]);

    await synchronizeVersions(root);

    const contents = await managedContents(root);
    expect(contents.cargo).toBe(cargoFixture("0.1.1").replaceAll("\n", "\r\n"));
    expect(contents.cargoLock).toBe(
      lockFixture({ appVersion: "0.1.1", coreVersion: "0.1.1" }).replaceAll(
        "\n",
        "\r\n",
      ),
    );
    expect(contents.packageJson).toBe(
      packageFixture("0.1.1").replaceAll("\n", "\r\n"),
    );
  });

  it("reports every drifted projection in deterministic order", async () => {
    const root = await projectFixture();

    await expect(checkVersions(root)).rejects.toThrow(
      "package.json=0.1.0, Cargo.toml=0.1.0, Cargo.lock:ai-router-app=0.1.0, Cargo.lock:router-core=0.1.0",
    );
  });

  it("rejects malformed authoritative and projected versions", async () => {
    const malformedSource = await projectFixture({ tauriVersion: "v0.1.1" });
    const malformedLock = await projectFixture({ appLockVersion: "v0.1.0" });

    await expect(synchronizeVersions(malformedSource)).rejects.toThrow(
      "valid stable SemVer",
    );
    await expect(checkVersions(malformedLock)).rejects.toThrow(
      "Cargo.lock:ai-router-app",
    );
  });

  it("rejects unsafe Cargo workspace and lockfile layouts", async () => {
    const missingWorkspace = await projectFixture();
    await writeFile(
      join(missingWorkspace, "Cargo.toml"),
      "[workspace]\nmembers = []\n",
    );

    const duplicatePackage = await projectFixture();
    await writeFile(
      join(duplicatePackage, "Cargo.lock"),
      `${lockFixture({ appVersion: "0.1.0", coreVersion: "0.1.0" })}\n[[package]]\nname = "router-core"\nversion = "0.1.0"\n`,
    );

    const sourcedPackage = await projectFixture();
    await writeFile(
      join(sourcedPackage, "Cargo.lock"),
      lockFixture({
        appVersion: "0.1.0",
        coreVersion: "0.1.0",
        sourceApp: true,
      }),
    );

    await expect(checkVersions(missingWorkspace)).rejects.toThrow(
      "[workspace.package]",
    );
    await expect(synchronizeVersions(duplicatePackage)).rejects.toThrow(
      "exactly one local package stanza for router-core",
    );
    await expect(synchronizeVersions(sourcedPackage)).rejects.toThrow(
      "ai-router-app must be source-less",
    );
  });

  it("rejects an ambiguous package version before writing destinations", async () => {
    const root = await projectFixture();
    await writeFile(
      join(root, "package.json"),
      '{"name":"fixture","metadata":{"version":"nested-only"}}\n',
    );
    const before = await managedContents(root);

    await expect(synchronizeVersions(root)).rejects.toThrow(
      "exactly one top-level version",
    );
    await expect(managedContents(root)).resolves.toEqual(before);
  });

  it("cleans staged files when a write fails before publication", async () => {
    const root = await projectFixture();
    const before = await managedContents(root);
    let writes = 0;

    await expect(
      synchronizeVersions(root, {
        fileSystem: {
          async writeFile(path, content, options) {
            writes += 1;
            if (writes === 2) {
              await writeFile(path, "partial", options);
              throw new Error("synthetic stage failure");
            }
            return writeFile(path, content, options);
          },
        },
      }),
    ).rejects.toThrow("could not publish projected files");

    await expect(managedContents(root)).resolves.toEqual(before);
    await expect(temporarySiblings(root)).resolves.toEqual([]);
  });

  it("leaves only detectable complete-file drift after a later rename fails", async () => {
    const root = await projectFixture();
    let renames = 0;

    await expect(
      synchronizeVersions(root, {
        fileSystem: {
          async rename(from, to) {
            renames += 1;
            if (renames === 2) throw new Error("synthetic publish failure");
            return rename(from, to);
          },
          unlink,
        },
      }),
    ).rejects.toThrow("could not publish projected files");

    const contents = await managedContents(root);
    expect(JSON.parse(contents.packageJson).version).toBe("0.1.1");
    expect(contents.cargo).toBe(cargoFixture("0.1.0"));
    await expect(checkVersions(root)).rejects.toThrow("Run pnpm version:sync");
    await expect(temporarySiblings(root)).resolves.toEqual([]);
  });
});
